models/Employee.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yiidreamteam\upload\ImageUploadBehavior;

/**
 * This is the model class for table "employee".
 *
 * @property integer $id
 * @property string $firstname
 * @property string $lastname
 * @property string $post
 * @property string $description
 * @property string $photo
 * @property integer $position
 * @property integer $created_at
 * @property integer $updated_at
 */
class Employee extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'employee';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            [
                'class' => ImageUploadBehavior::class,
                'attribute' => 'photo',
                'filePath' => '@webroot/uploads/image_[[pk]].[[extension]]',
                'fileUrl' => '/uploads/image_[[pk]].[[extension]]'
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['firstname', 'lastname'], 'required'],
            [['description'], 'string'],
            [['position', 'created_at', 'updated_at'], 'integer'],
            [['firstname', 'lastname', 'post'], 'string', 'max' => 255],
            ['photo', 'file', 'extensions' => 'jpeg, jpg, gif, png']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'firstname' => Yii::t('app', 'Firstname'),
            'lastname' => Yii::t('app', 'Lastname'),
            'post' => Yii::t('app', 'Post'),
            'description' => Yii::t('app', 'Description'),
            'photo' => Yii::t('app', 'Photo'),
            'position' => Yii::t('app', 'Position'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return string
     */
    public function getFullname()
    {
        return $this->lastname.' '.$this->firstname;
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Employee;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    //'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     * @return string|Response
     * @throws Exception
     * @throws \yii\base\ExitException
     */
    public function actionContact()
    {
        if(\Yii::$app->request->isAjax){
            $model = new ContactForm();
            if ($model->load(Yii::$app->request->post()) && $model->contact(\Yii::$app->params['sendTo'])) {
                echo \Yii::$app->params['messages']['success'];
                \Yii::$app->end();
            }
        }
        throw new Exception('Error');
    }

    /**
     * Раздел "Разработка"
     * @return string
     */
    public function actionDevelopment()
    {
        return $this->render('development');
    }

    /**
     * Раздел "О нас"
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about', [
            'employees' => Employee::find()->orderBy('position')->all()
        ]);
    }

    public function actionProducts()
    {
        return $this->render('products');
    }

    public function actionEqueo()
    {
        return $this->render('equeo');
    }

    public function action4kam()
    {
        return $this->render('4kam');
    }

    public function actionMyteam()
    {
        return $this->render('myteam');
    }

    public function actionTakeda()
    {
        return $this->render('takeda');
    }

    public function actionLafarge()
    {
        return $this->render('lafarge');
    }
}

views/site/4kam.php
<?php
/** @var $this \yii\web\View */

$this->title = '4kam';
?>
<div class="container-fluid main">
    <header class="main-header light-blue">
        <div class="logo-title content-indent">
            <h3 class="text-uppercase"><a href="/">центр&#13;&#10;мобильной<br>разработки </a><span
                    class="main-menu-toggle visible-xs pull-right"><svg viewBox="0 0 800 600"><path
                            d="M300,220 C300,220 520,220 540,220 C740,220 640,540 520,420 C440,340 300,200 300,200"
                            id="top"></path><path d="M300,320 L540,320" id="middle"></path><path
                            d="M300,210 C300,210 520,210 540,210 C740,210 640,530 520,410 C440,330 300,190 300,190"
                            id="bottom"
                            transform="translate(480, 320) scale(1, -1) translate(-480, -318) "></path></svg></span>
            </h3>
        </div>
        <hr>
        <div class="header-logo-container text-center text-uppercase"><a class="header-logo" href="/"><img
                    src="/assets/context/ready-mades-01-7.png"></a></div>
        <div class="row">
            <div class="col-sm-12 product-logo-container"><img class="img-responsive center-block"
                                                               src="/assets/context/products/4kam/header-logo.png"></div>
        </div>
    </header>
    <div class="main-content">
        <section class="description-section content-indent">
            <div class="row">
                <div class="col-sm-12"><p class="core-sans-a35-light text-center">Модный и технологичный продукт,
                        который помогает менеджерам по работе с ключевыми клиентами Henkel планировать объемы отгрузок и
                        промо-кампании, контролировать листинг, мгновенно получать информацию по нужным показателям.
                        Приоритеты заказчика — создание удобной и быстрой программы, понятной даже новичку в сегменте
                        FMCG.</p></div>
            </div>
            <div class="row screenshots-row">
                <div class="img-responsive center-block screenshot-left"
                     style="height: 350px; background-color: #35556b"></div>
                <div class="img-responsive center-block screenshot-right"
                     style="height: 350px; background-color: #8cced5"></div>
            </div>
        </section>
        <section class="content-indent">
            <div class="section-header-container text-center"><h1 class="section-header text-uppercase">Функционал</h1>
            </div>
            <p class="core-sans-a35-light text-center">Сотрудник Henkel гибко управляет сетями, выставляя объемы
                отгружаемой продукции по каждой позиции каталога, держит под контролем мгновенно расчитываемый
                показатель PC, заводит и согласовывает промо-кампании, планирует развитие листинга на периоде и
                проверяет листинг по продажам. В 4KAM реализована ролевая структура, благодаря которой руководство в HQ
                имеет возможность утверждать кампании, ставить цели по показателям и KPI и управлять ассортиментом.</p>
        </section>
        <section class="screenshots-section kam content-indent">
            <div class="screenshots-container single"><img class="img-responsive"
                                                           src="/assets/context/products/4kam/screen-1.png"></div>
        </section>
        <section class="screenshots-section kam-2 content-indent">
            <div class="screenshots-tablet"><img class="img-responsive" src="/assets/context/products/4kam/screen-2.png">
            </div>
        </section>
        <section class="facts-section kam content-indent">
            <div class="facts-container">
                <div class="facts-header-container text-center"><h1 class="section-header text-uppercase">Факты</h1>
                </div>
                <div class="row">
                    <div class="col-sm-4 text-center"><h1 class="core-sans-a25-extra-light big red" data-grow="200">>
                            <span></span></h1>
                        <p class="core-sans-a55-medium small">Менеджеров по работе с ключевыми<br>клиентамиработает в
                            программе</p></div>
                    <div class="col-sm-4 text-center"><h1 class="core-sans-a25-extra-light big red" data-grow="457">
                            <span></span></h1>
                        <p class="core-sans-a55-medium small">Национальных и региональных<br>сетей,куда производятся<br>отгрузки
                            товаров Henkel</p></div>
                    <div class="col-sm-4 text-center"><h1 class="core-sans-a25-extra-light big red" data-grow="375">
                            <span></span></h1>
                        <p class="core-sans-a55-medium small">Товарных позиций, по которым<br>проводится планирование
                        </p></div>
                </div>
            </div>
        </section>
        <?= $this->render('_footer');?>
    </div>
</div>
<?=$this->render('menu', ['style' => '']);?>

views/site/_footer.php
<footer class="main-footer content-indent">
    <div class="footer-logo-container text-center">
        <div class="footer-logo"><img src="/assets/context/ready-mades-01-7.png"></div>
    </div>
    <div class="row">
        <div class="col-sm-6 footer-text footer-left-text"><h2 class="core-sans-a65-bold red">Всегда рады<br>общению!
            </h2></div>
        <div class="col-sm-6 footer-text footer-right-text core-sans-a25-extra-light"><h2
                class="footer-text-phone">+7 (969) 656 73 26</h2>
            <h2 class="footer-text-email">welcomе@r-mades.com</h2>
            <h3 class="address">400136, г.Волгоград, ул.&nbsp;Канунникова,<br>д.23, БЦ Дельта</h3>
            <h3 class="address">107140, г. Москва, ул. Русаковская,<br>д.13, БЦ Бородино Плаза</h3></div>
    </div>
    <div class="row">
        <div class="col-sm-12 social"><img src="/assets/context/social/google-plus.png"> <img
                src="/assets/context/social/vk.png"> <a href="https://www.facebook.com/readymadesmobile/"
                                                       target="_blank"><img
                    src="/assets/context/social/facebook.png"></a></div>
    </div>
    <div class="copyright text-uppercase text-center"><img src="/assets/context/coffee-man.png"><h5
            class="core-sans-a35-light text-normal">© all rights reserved</h5></div>
</footer>

views/site/about.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Html;
$this->title = 'О нас';
?>
    <div class="container-fluid main">
        <header class="main-header blue text-uppercase">
            <div class="logo-title content-indent">
                <h3>
                    <a href="/">
                        центр&#13;&#10;мобильной <br/> разработки
                    </a>
                    <span class="main-menu-toggle visible-xs pull-right">
                            <svg viewBox="0 0 800 600">
                            <path d="M300,220 C300,220 520,220 540,220 C740,220 640,540 520,420 C440,340 300,200 300,200" id="top"></path>
                            <path d="M300,320 L540,320" id="middle"></path>
                            <path d="M300,210 C300,210 520,210 540,210 C740,210 640,530 520,410 C440,330 300,190 300,190" id="bottom" transform="translate(480, 320) scale(1, -1) translate(-480, -318) "></path>
                            </svg>
                        </span>
                </h3>
            </div>
            <hr />
            <div class="header-logo-container text-center">
                <a href="/" class="hidden-xs">главная</a>
                <div class="header-logo">
                    <img src="assets/context/ready-mades-01-2.png"/>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12 text-uppercase text-center">
                    <h1 class="header-title">о нас</h1>
                </div>
            </div>
        </header>
        <div class="main-content">
            <section class="content-indent">
                <div class="row">
                    <div class="col-sm-12">
                        <p class="core-sans-a35-light text-center">
                            Мы знаем, что работа в команде, при разработке сложных инновационных
                            продуктов&nbsp;-&nbsp;это сложный процесс. Мы знаем сколько автотестов прогояется
                            на&nbsp;устройстве в&nbsp;день, сколько задач попадает в&nbsp;сервисдеск
                            и&nbsp;сколько команда&nbsp;iOS&nbsp;выпивает редбула перед релизом.
                        </p>
                    </div>
                </div>
            </section>

            <section class="team content-indent">
                <div class="row">
                    <div class="col-sm-4 text-center">
                        <h1 class="core-sans-a25-extra-light big red" data-grow="60">> <span></span>
                        </h1>
                        <p class="core-sans-a55-medium small">
                            Именно столько сотрудников<br />
                            работает в центре: руководители<br />
                            проектов, разработчики, тестировщики,<br />
                            UI/UX проектировщики, дизайнеры,<br />
                            аналитики.
                        </p>
                    </div>
                    <div class="col-sm-4 text-center">
                        <h1 class="core-sans-a25-extra-light big red" data-grow="55"><span></span>+</h1>
                        <p class="core-sans-a55-medium small">
                            IT-проектов, в которых приняли<br />
                            участие наши специалисты.<br />
                            Логистика, ритейл, финансы,<br />
                            здравоохранение, сфера услуг,<br />
                            gamedev.
                        </p>
                    </div>
                    <div class="col-sm-4 text-center">
                        <h1 class="core-sans-a25-extra-light big red" data-grow="7.5"><span></span> лет</h1>
                        <p class="core-sans-a55-medium small">
                            Средний стаж работы нашей<br />
                            команды. Эффективное сочетание<br />
                            теоретической подкованности<br />
                            и практических компетенций.<br />
                        </p>
                    </div>
                </div>

                <div class="person-container">
                    <?php if(count($employees) > 0):?>
                        <?php foreach ($employees as $employee):?>
                            <figure class="person">
                                <p><?= Html::img($employee->getImageFileUrl('photo'), ['width' => 230]);?></p>
                                <figcaption>
                                    <span><?= $employee->fullname;?><br />
                                    <?= $employee->post;?></span>
                                    <div class="details"><?= $employee->description;?></div>
                                </figcaption>
                            </figure>
                        <?php endforeach;?>
                    <?php endif;?>
                </div>
                <div class="be-with-us">
                    <figure class="person">
                        <h1 class="core-sans-a65-bold text-center">+</h1>
                        <p class="core-sans-a25-extra-light text-center text-uppercase">будь с нами !</p>
                    </figure>
                </div>
            </section>

            <footer class="main-footer content-indent">
                <div class="footer-logo-container text-center">
                    <div class="footer-logo">
                        <img src="assets/context/ready-mades-01-7.png"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6 footer-text footer-left-text">
                        <h2 class="core-sans-a65-bold red">Всегда рады <br/> общению!</h2>
                    </div>
                    <div class="col-sm-6 footer-text footer-right-text core-sans-a25-extra-light">
                        <h2 class="footer-text-phone">+7 (969) 656 73 26</h2>
                        <h2 class="footer-text-email">welcomе@r-mades.com</h2>
                        <h3 class="address">400136, г.Волгоград, ул.&nbsp;Канунникова,<br/>д.23, БЦ Дельта</h3>
                        <h3 class="address">107140, г. Москва, ул. Русаковская,<br/>д.13, БЦ Бородино Плаза</h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12 social">
                        <img src="assets/context/social/google-plus.png" />
                        <img src="assets/context/social/vk.png" />
                        <a href="https://www.facebook.com/readymadesmobile/" target="_blank">
                            <img src="assets/context/social/facebook.png" />
                        </a>
                    </div>
                </div>
                <div class="copyright text-uppercase text-center">
                    <img src="assets/context/coffee-man.png"/>
                    <h5 class="core-sans-a35-light text-normal">© all rights reserved</h5>
                </div>
            </footer>
        </div>
    </div>
<?= $this->render('menu', ['style' => '']);

views/site/contact.php
<?php
/* @var $this yii\web\View */
/* @var $form app\models\ContactForm */

use yii\helpers\Html;
use yii\helpers\Url;
?>
<?= Html::beginForm('/', 'POST', [
        'id' => 'contact-form',
        'class' => ''
]);?>
    <div class="col-xs-12 col-sm-8 col-md-4">
        <div class="hidden-xs splitter"></div>
        <?= Html::label('Имя', 'ContactForm[name]', ['class' => 'sr-only']);?>
        <?= Html::input('text', 'ContactForm[name]', null, [
            'id' => 'form-name',
            'class' => 'form-control',
            'placeholder' => 'имя'
        ]); ?>
    </div>
    <div class="col-xs-12 col-sm-offset-4 col-sm-8 col-md-offset-0 col-md-4 upper-top-sm">
        <?= Html::label('Телефон', 'ContactForm[phone]', ['class' => 'sr-only']);?>
        <?= Html::input('text', 'ContactForm[phone]', null, [
            'id' => 'form-phone',
            'class' => 'form-control',
            'placeholder' => 'телефон'
        ]); ?>
    </div>
    <div class="col-xs-12 col-sm-offset-4 col-sm-8 col-md-offset-0 col-md-4">
        <button type="submit" class="btn btn-primary"><span
                    class="visible-xs">Оставить заявку</span> <span class="hidden-xs">Отправить</span>
        </button>
    </div>
<?= Html::endForm();?>
<?php
$url = Url::to(['contact']);
$error = \Yii::$app->params['messages']['error'];
$js = <<< JS
    $(document).ready(function(){        
        $("#contact-form").on("submit", function(){
            var name = $("#form-name").val();
            var phone = $("#form-phone").val();
            
            if(name && phone){
                $.ajax({
                    url: "{$url}",
                    method: "POST",
                    data: $(this).serialize(),
                }).done(function(message){
                    iziToast.success({
                        title: 'Отправлено',
                        message: message,
                        position: 'center',
                        timeout:  5000,
                        layout: 2
                    });
                    
                }).fail(function(message) {
                    iziToast.error({
                        title: 'Ошибка',
                        message: "{$error}",
                        position: 'center'
                    });
                });
                
                $(".hide-contact-us").trigger('click');
                $(this).trigger('reset');
            }
            return false;
        });  
    });
JS;
$this->registerJs($js, \yii\web\View::POS_END);

views/site/equeo.php
<?php
/** @var $this \yii\web\View */

$this->title = 'equeo';
?>
<div class="container-fluid main">
    <header class="main-header dark-blue">
        <div class="logo-title content-indent">
            <h3 class="text-uppercase"><a href="/">центр&#13;&#10;мобильной<br>разработки </a><span
                    class="main-menu-toggle visible-xs pull-right"><svg viewBox="0 0 800 600"><path
                            d="M300,220 C300,220 520,220 540,220 C740,220 640,540 520,420 C440,340 300,200 300,200"
                            id="top"></path><path d="M300,320 L540,320" id="middle"></path><path
                            d="M300,210 C300,210 520,210 540,210 C740,210 640,530 520,410 C440,330 300,190 300,190"
                            id="bottom"
                            transform="translate(480, 320) scale(1, -1) translate(-480, -318) "></path></svg></span>
            </h3>
        </div>
        <hr>
        <div class="header-logo-container text-center text-uppercase"><a class="header-logo" href="/"><img
                    src="/assets/context/ready-mades-alt-01-2.png"></a></div>
        <div class="row">
            <div class="col-sm-12 product-logo-container"><img class="img-responsive center-block"
                                                               src="/assets/context/products/equeo/header-logo.png">
                <p class="core-sans-a35-light text-center">Платформа для обучения и бизнес-коммуникации e.Queo</p></div>
        </div>
    </header>
    <div class="main-content">
        <section class="description-section content-indent">
            <div class="row">
                <div class="col-sm-12"><p class="core-sans-a35-light text-center">Основная идея e.Queo — перенос
                        традиционного обучения сотрудников в цифровую среду. Персонал должен иметь быстрый и удобный
                        доступ к обучающим материалам, онлайн-аттестациям и статистике по их прохождению. Упор делается
                        на видео-контент премиум качества и нативные мобильные приложения для iOS и Android.</p></div>
            </div>
            <div class="row screenshots-row">
                <div class="img-responsive center-block screenshot-left"
                     style="height: 350px; background-color: #35556b"></div>
                <div class="img-responsive center-block screenshot-right"
                     style="height: 350px; background-color: #8cced5"></div>
            </div>
        </section>
        <section class="content-indent">
            <div class="section-header-container text-center"><h1 class="section-header text-uppercase">Функционал</h1>
            </div>
            <p class="core-sans-a35-light text-center">«Учись» — каталог профессионально созданных видеотренингов с
                финальными тестами. «Узнавай» — лента видео для микро-обучения и тренировки soft skills. «Аттестация» —
                проверка знаний и опросы. Также пользователю доступен раздел с дополнительной информацией (каталоги,
                памятки, планограммы) для эффективной работы вне офиса.</p></section>
        <section class="screenshots-section equeo content-indent">
            <div class="screenshots-container"><img class="screenshot" src="/assets/context/products/equeo/phone-1.png">
                <img class="screenshot" src="/assets/context/products/equeo/phone-2.png"> <img class="screenshot"
                                                                                              src="/assets/context/products/equeo/phone-1.png">
            </div>
        </section>
        <section class="screenshots-section equeo-2 content-indent">
            <div class="screenshots-tablet"><img class="img-responsive"
                                                 src="/assets/context/products/equeo/tablet-1.png"></div>
        </section>
        <section class="facts-section equeo content-indent">
            <div class="facts-container">
                <div class="facts-header-container text-center"><h1 class="section-header text-uppercase">Факты</h1>
                </div>
                <div class="row">
                    <div class="col-sm-4 text-center"><h1 class="core-sans-a25-extra-light big red" data-grow="2.5">>
                            <span></span>K</h1>
                        <p class="core-sans-a55-medium small">Сотрудников в сфере<br>FMCG используют наше решение</p>
                    </div>
                    <div class="col-sm-4 text-center"><h1 class="core-sans-a25-extra-light big red" data-grow="20">
                            <span></span>+</h1>
                        <p class="core-sans-a55-medium small">Человек обеспечивают<br>техническую поддержку<br>пользователей
                            в рабочее время</p></div>
                    <div class="col-sm-4 text-center">
                        <h1 class="core-sans-a25-extra-light big red" data-grow="7"><span></span>
                            <small class="red text-uppercase">new</small>
                        </h1>
                        <p class="core-sans-a55-medium small">Глобальных
                            обновлений<br>приложения мы осуществили<br>с 2015 года</p></div>
                </div>
            </div>
        </section>
        <?= $this->render('_footer');?>
    </div>
</div>
<?=$this->render('menu', ['style' => '']);?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */
/* @var $form \app\models\ContactForm */
use yii\helpers\Html;

$this->title = 'R-mades';
?>
<div class="container-fluid main">
    <div class="main-content-full">
        <div class="main-center-name content-indent">
            <h3 class="text-uppercase">центр&#13;&#10;мобильной<br>разработки <span
                        class="main-menu-toggle black visible-xs pull-right"><svg viewBox="0 0 800 600"><path
                                d="M300,220 C300,220 520,220 540,220 C740,220 640,540 520,420 C440,340 300,200 300,200"
                                id="top"></path><path d="M300,320 L540,320" id="middle"></path><path
                                d="M300,210 C300,210 520,210 540,210 C740,210 640,530 520,410 C440,330 300,190 300,190"
                                id="bottom" transform="translate(480, 320) scale(1, -1) translate(-480, -318) "></path></svg></span>
            </h3>
        </div>
        <div class="main-logo"></div>
        <div class="main-navigation main-navigation-left text-uppercase">продукты</div>
        <div class="main-navigation main-navigation-right text-uppercase">о нас</div>
        <div class="main-navigation main-navigation-bottom text-uppercase"><a href="/development">разработка</a>
        </div>
    </div>
</div>
<?= $this->render('menu', ['style' => '']);?>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>